export enum LoggerContext {
    Account = 'Account',
    Auth = 'Auth',
    Chart = 'Chart',
    Chat = 'Chat',
    Contact = 'Contact',
    Console = 'Console',
    Currencies = 'Currencies',
    Dashboard = 'Dashboard',
    Dpop = 'DPoP',
    Home = 'Home',
    Navigation = 'Navigation',
    Portfolio = 'Portfolio',
    Simulator = 'Simulator',
    Statistics = 'Statistics',
    System = 'System',
    Table = 'Table',
    Terms = 'Terms',
    Trade = 'Trade',
    Trader = 'Trader',
}