"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from os import getenv
from pathlib import Path
from crypto_trader_analysis.core.aws_secrets import SecretsManagerService


def csv_setting(value: str, default: list[str] | None = None) -> list[str]:
    if value is None:
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]


def secret_or_env(name: str, default=None):
    return crypto_trader_secrets.get(name, getenv(name, default))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

secrets_service = SecretsManagerService(region_name="us-east-1")

try:
    crypto_trader_secrets = secrets_service.get_secret("/cryptotrader/dev")
except Exception as exception:
    crypto_trader_secrets = {}
    if not os.getenv("DEBUG", "True") == "True":
        raise exception

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = crypto_trader_secrets.get("DJANGO_SECRET_KEY", os.getenv("DJANGO_SECRET_KEY", "fallback-if-dev"))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = csv_setting(secret_or_env("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1"))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crypto_trader_analysis.api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crypto_trader_analysis.api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': crypto_trader_secrets.get('PSQL_DB_NAME', 'crypto_trader'),
        'USER': crypto_trader_secrets.get('PSQL_USER', getenv('PSQL_USER')),
        'PASSWORD': crypto_trader_secrets.get('PSQL_PW', getenv('PSQL_PW')),
        'HOST': crypto_trader_secrets.get('PSQL_HOST', getenv('PSQL_HOST')),
        'PORT': crypto_trader_secrets.get('PSQL_PORT', '5432')
    }
}

OPENAI_KEY = crypto_trader_secrets.get("OPENAI_KEY")
GITHUB_TOKEN = crypto_trader_secrets.get("GITHUB_TOKEN")
JWT_SECRET = crypto_trader_secrets.get("JWT_SECRET")
WORLDNEWS_API_KEY = secret_or_env("WORLDNEWS_API_KEY")
CT_API_HOST = secret_or_env("CT_API_HOST", "localhost")
CT_DATA_HOST = secret_or_env("CT_DATA_HOST", "localhost")
CT_API_BASE_URL = secret_or_env("CT_API_BASE_URL", f"https://{CT_API_HOST}:8080")
CT_DATA_BASE_URL = secret_or_env("CT_DATA_BASE_URL", f"https://{CT_DATA_HOST}:8085")
CT_CA_BUNDLE = secret_or_env("CT_CA_BUNDLE", None)
CT_SERVICE_TIMEOUT_SECONDS = float(secret_or_env("CT_SERVICE_TIMEOUT_SECONDS", "15"))


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CSRF_TRUSTED_ORIGINS = csv_setting(
    secret_or_env(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "https://localhost:8080,https://127.0.0.1:8080,https://localhost:8085,https://127.0.0.1:8085",
    )
)

CORS_ALLOWED_ORIGINS = csv_setting(
    secret_or_env("DJANGO_CORS_ALLOWED_ORIGINS", "https://localhost:8085,https://localhost:8080")
)

SECURE_SSL_REDIRECT = secret_or_env("DJANGO_SECURE_SSL_REDIRECT", "False") == "True"
SESSION_COOKIE_SECURE = secret_or_env("DJANGO_SESSION_COOKIE_SECURE", "False") == "True"
CSRF_COOKIE_SECURE = secret_or_env("DJANGO_CSRF_COOKIE_SECURE", "False") == "True"
SECURE_HSTS_SECONDS = int(secret_or_env("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = secret_or_env("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "False") == "True"
SECURE_HSTS_PRELOAD = secret_or_env("DJANGO_SECURE_HSTS_PRELOAD", "False") == "True"
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
